[tool.poetry]
name = "wts"
version = "0.3.2"
description = "Workspace Token Service"
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
alembic = "^1.4.1"
Authlib = "^0.14.3"
authutils = "^5.0.5"
cdiserrors = "^1.0.0"
cdislogging = "^1.0.0"
cryptography = "2.8"
Flask = {version = "^2.1.3", extras = ["async"]}
Flask-SQLAlchemy = "^2.3.0"
kubernetes = "^11.0.0"
psycopg2 = "^2.7.0"
python-jose = "^3.0.0"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
codacy-coverage = "*"
mock = ">=4.0.2"
PyGithub = "*"
pytest = ">=6.0.1"
pytest-cov = ">=2.10.1"
pytest-flask = ">=1.0.0"
respx = ">=0.17.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
